#!/bin/sh

# 변경된 파일들 이름 추출 (staged 파일만)
stagedFiles=$(git diff --staged --name-only)

# SpotlessApply 실행
echo "Running spotlessApply. Formatting code..."

./gradlew spotlessApply --daemon
if [ $? -ne 0 ]; then
  echo "spotlessApply failed. Please check the error message."
  exit 1
fi

# 다시 변경된 파일들 이름 추출
for file in $stagedFiles; do
  if test -f "$file"; then
    git add "$file"
  fi
done
