INSERT INTO problem (title, question, solution, point, level, solved, percentage, created_date, modified_date)
VALUES
    ('Solve for x', 'What is the value of x in the equation 2x + 3 = 7?', 'x = 2', 10, 1, 100, 90.0, NOW(), NOW()),
    ('Find the area', 'What is the area of a triangle with base 5 and height 3?', 'Area = 7.5', 15, 1, 150, 95.0, NOW(), NOW()),
    ('Sort an array', 'Sort the given array in ascending order.', 'Use quicksort algorithm', 20, 2, 200, 85.0, NOW(), NOW()),
    ('Binary Search', 'Find the position of target value in a sorted array using binary search.', 'Use binary search algorithm', 25, 2, 250, 80.0, NOW(), NOW()),
    ('Calculate velocity', 'What is the velocity of an object moving with constant acceleration?', 'Use v = u + at', 15, 1, 180, 88.0, NOW(), NOW()),
    ('Ohm\'s Law', 'Calculate the current in a circuit with resistance R and voltage V.', 'Use I = V/R', 20, 1, 160, 92.0, NOW(), NOW()),
    ('Functional Groups', 'Identify the functional groups in the given organic molecule.', 'List the functional groups', 15, 2, 140, 87.0, NOW(), NOW()),
    ('Periodic Table', 'Identify the elements in the given group of the periodic table.', 'List the elements', 10, 1, 120, 91.0, NOW(), NOW()),
    ('Punnett Square', 'Determine the genotypic ratio for the given cross.', 'Draw the Punnett square', 15, 1, 130, 89.0, NOW(), NOW()),
    ('Natural Selection', 'Explain the principle of natural selection.', 'Describe how natural selection works', 20, 2, 110, 85.0, NOW(), NOW()),
    ('Matrix Multiplication', 'Multiply the given matrices.', 'Provide the resulting matrix', 25, 2, 170, 83.0, NOW(), NOW()),
    ('Pythagorean Theorem', 'Find the length of the hypotenuse in a right triangle with legs a and b.', 'Use c = sqrt(a^2 + b^2)', 10, 1, 140, 94.0, NOW(), NOW()),
    ('Dijkstra\'s Algorithm', 'Find the shortest path in the given graph.', 'Use Dijkstra\'s algorithm', 30, 3, 90, 82.0, NOW(), NOW()),
    ('Linked List', 'Implement a singly linked list.', 'Provide the implementation code', 20, 2, 160, 86.0, NOW(), NOW()),
    ('Newton\'s Second Law', 'Calculate the force on an object with mass m and acceleration a.', 'Use F = ma', 15, 1, 150, 90.0, NOW(), NOW()),
    ('Faraday\'s Law', 'Calculate the induced emf in a coil with N turns and changing magnetic flux.', 'Use emf = -N dΦ/dt', 25, 2, 130, 88.0, NOW(), NOW()),
    ('Reaction Mechanism', 'Determine the mechanism of the given organic reaction.', 'Provide the step-by-step mechanism', 20, 3, 120, 84.0, NOW(), NOW()),
    ('Chemical Bonding', 'Explain the type of bonding in the given compound.', 'Describe the bonding type', 15, 1, 170, 93.0, NOW(), NOW()),
    ('Genetic Code', 'Translate the given mRNA sequence into an amino acid sequence.', 'Use the genetic code table', 20, 2, 180, 87.0, NOW(), NOW()),
    ('Evolutionary Trees', 'Construct an evolutionary tree based on the given data.', 'Draw the evolutionary tree', 25, 3, 140, 81.0, NOW(), NOW());
